---
extends: default

ignore: |
  .venv/
  batfish/
  inventory/intended/

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 140
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
