---
all:
  children:
    CONTAINERLAB:
      hosts:
        CL_1:
          ansible_host: 10.255.8.45
      vars:
        ansible_user: ansible
        ansible_password: ansible
        ansible_become_password: ansible
        containerlab_include_intfs_to_non_avd_nodes: false
        containerlab_ceos_version: ceosimage:4.28.4M
        containerlab_mgmt_network: 192.168.0.0/24
        containerlab_custom_interface_mapping: true
        containerlab_mode: 'installed'
    CVP:
      hosts:
        cv_server:
          ansible_httpapi_host: 10.65.2.9
          ansible_host: 10.65.2.9
        CVP-1-SSH:
      vars:
        ansible_user: cvpadmin
        ansible_password: ChangeMe!@34
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: eos
        ansible_httpapi_port: 443
        ansible_python_interpreter: $(which python3)
        cv_collection: v3
    AMS:
      children:
        AMS_SUPER_SPINES:
          hosts:
            SUPER-SPINE1:
              type: super-spine
              ansible_host: 10.66.5.12
              mgmt_gateway: 10.66.5.1
        DC1:
          children:
            DC1_POD1:
              children:
                DC1_POD1_SPINES:
                  hosts:
                    DC1-POD1-SPINE1:
                      type: spine
                      ansible_host: 10.66.1.11
                      mgmt_gateway: 10.66.1.1
                    DC1-POD1-SPINE2:
                      type: spine
                      ansible_host: 10.66.2.11
                      mgmt_gateway: 10.66.2.1
                    DC1-POD1-SPINE3:
                      type: spine
                      ansible_host: 10.66.5.13
                      mgmt_gateway: 10.66.5.1
                DC1_POD1_LEAFS:
                  hosts:
                    DC1-POD1-LEAF3A:
                      type: l3leaf
                      ansible_host: 10.66.3.10
                      mgmt_gateway: 10.66.3.1
                      vlan100: 10.64.3.1/24
                      vlan67: 10.65.3.1/24
                      vlan33: 10.65.131.1/24
                    DC1-POD1-LEAF5A:
                      type: l3leaf
                      ansible_host: 10.66.5.11
                      vlan100: 10.64.5.1/24
                      vlan67: 10.65.5.1/24
                      vlan33: 10.65.133.1/24
                      mgmt_gateway: 10.66.5.1
                    DC1-POD1-LEAF6A:
                      type: l3leaf
                      ansible_host: 10.66.3.16
                      vlan100: 10.64.6.1/24
                      vlan67: 10.65.6.1/24
                      vlan33: 10.65.134.1/24
                      mgmt_gateway: 10.66.6.1
                    DC1-POD1-LEAF7A:
                      type: l3leaf
                      ansible_host: 10.66.3.17
                      vlan100: 10.64.7.1/24
                      vlan67: 10.65.7.1/24
                      vlan33: 10.65.135.1/24
                      mgmt_gateway: 10.66.7.1

      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_host: '{{ ansible_host }}'
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: arista.eos.eos
        ansible_user: cvpadmin
        ansible_ssh_pass: ChangeMe!@34
        ansible_become: true
        ansible_become_method: enable
        ansible_python_interpreter: $(which python3)
        cv_collection: v3

    # Needed for who can reference the values:
    TENANTS_NETWORKS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
        DC2_POD1_LEAFS:

    SERVERS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
        DC2_POD1_LEAFS:
    # Using this for edge's like mgmt
    ROUTERS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
    FIREWALLS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
