---
all:
  children:
    CVP:
      hosts:
        cv_server:
          ansible_httpapi_host: 10.65.2.9
          ansible_host: 10.65.2.9
        CVP-1-SSH:
      vars:
        ansible_user: cvpadmin
        ansible_password: ChangeMe!@34
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: eos
        ansible_httpapi_port: 443
        ansible_python_interpreter: $(which python3)
        cv_collection: v3
    AMS:
      children:
        AMS_SUPER_SPINES:
          hosts:
            SUPER-SPINE1:
              type: super-spine
              ansible_host: 10.6.0.10
            SUPER-SPINE2:
              type: super-spine
              ansible_host: 10.6.0.11
            SUPER-SPINE3:
              type: super-spine
              ansible_host: 10.6.0.12
            SUPER-SPINE4:
              type: super-spine
              ansible_host: 10.6.0.13
              # SUPER-SPINE5:
              #   type: super-spine
              #   ansible_host: 10.6.0.14
        DC1:
          children:
            DC1_POD1:
              children:
                DC1_POD1_SPINES:
                  hosts:
                    DC1-POD1-SPINE1:
                      type: spine
                      ansible_host: 10.6.1.10
                    DC1-POD1-SPINE2:
                      type: spine
                      ansible_host: 10.6.1.11
                    DC1-POD1-SPINE3:
                      type: spine
                      ansible_host: 10.6.1.12
                    DC1-POD1-SPINE4:
                      type: spine
                      ansible_host: 10.6.1.13
                DC1_POD1_LEAFS:
                  hosts:
                    DC1-POD1-LEAF1A:
                      type: l3leaf
                      ansible_host: 10.6.1.20
                    DC1-POD1-LEAF1B:
                      type: l3leaf
                      ansible_host: 10.6.1.21
                    DC1-POD1-LEAF2A:
                      type: l3leaf
                      ansible_host: 10.6.1.22
                    DC1-POD1-LEAF2B:
                      type: l3leaf
                      ansible_host: 10.6.1.23
#                    DC1-POD1-L2LEAF1A:
#                      type: l2leaf
#                      ansible_host: 10.6.1.X
                    DC1-POD1-LEAF3A:
                      type: l3leaf
                      ansible_host: 10.6.1.24
                    DC1-POD1-LEAF3B:
                      type: l3leaf
                      ansible_host: 10.6.1.25
                    DC1-POD1-LEAF4A:
                      type: l3leaf
                      ansible_host: 10.6.1.26
                    DC1-POD1-LEAF4B:
                      type: l3leaf
                      ansible_host: 10.6.1.27
                    DC1-POD1-LEAF5A:
                      type: l3leaf
                      ansible_host: 10.6.1.28
                    DC1-POD1-LEAF5B:
                      type: l3leaf
                      ansible_host: 10.6.1.29
                    DC1-POD1-LEAF6A:
                      type: l3leaf
                      ansible_host: 10.6.1.30
                    DC1-POD1-LEAF6B:
                      type: l3leaf
                      ansible_host: 10.6.1.31
                    DC1-POD1-LEAF7A:
                      type: l3leaf
                      ansible_host: 10.6.1.32
                    DC1-POD1-LEAF7B:
                      type: l3leaf
                      ansible_host: 10.6.1.33
                    DC1-POD1-LEAF8A:
                      type: l3leaf
                      ansible_host: 10.6.1.34
                    DC1-POD1-LEAF8B:
                      type: l3leaf
                      ansible_host: 10.6.1.35
                    DC1-POD1-LEAF9A:
                      type: l3leaf
                      ansible_host: 10.6.1.36
                    DC1-POD1-LEAF9B:
                      type: l3leaf
                      ansible_host: 10.6.1.37
                    DC1-POD1-LEAF10A:
                      type: l3leaf
                      ansible_host: 10.6.1.38
                    DC1-POD1-LEAF10B:
                      type: l3leaf
                      ansible_host: 10.6.1.39
                    DC1-POD1-LEAF11A:
                      type: l3leaf
                      ansible_host: 10.6.1.40
                    DC1-POD1-LEAF11B:
                      type: l3leaf
                      ansible_host: 10.6.1.41
                    DC1-POD1-LEAF12A:
                      type: l3leaf
                      ansible_host: 10.6.1.42
                    DC1-POD1-LEAF12B:
                      type: l3leaf
                      ansible_host: 10.6.1.43
                    DC1-POD1-LEAF13A:
                      type: l3leaf
                      ansible_host: 10.6.1.44
                    DC1-POD1-LEAF13B:
                      type: l3leaf
                      ansible_host: 10.6.1.45
                    DC1-POD1-LEAF14A:
                      type: l3leaf
                      ansible_host: 10.6.1.46
                    DC1-POD1-LEAF14B:
                      type: l3leaf
                      ansible_host: 10.6.1.47
            DC1_POD2:
              children:
                DC1_POD2_SPINES:
                  hosts:
                    DC1-POD2-SPINE1:
                      type: spine
                      ansible_host: 10.6.33.10
                    DC1-POD2-SPINE2:
                      type: spine
                      ansible_host: 10.6.33.11
                    DC1-POD2-SPINE3:
                      type: spine
                      ansible_host: 10.6.33.12
                    DC1-POD2-SPINE4:
                      type: spine
                      ansible_host: 10.6.33.13
                DC1_POD2_LEAFS:
                  hosts:
                    DC1-POD2-LEAF1A:
                      type: l3leaf
                      ansible_host: 10.6.33.20
                    DC1-POD2-LEAF1B:
                      type: l3leaf
                      ansible_host: 10.6.33.21
                    DC1-POD2-LEAF2A:
                      type: l3leaf
                      ansible_host: 10.6.33.22
                    DC1-POD2-LEAF2B:
                      type: l3leaf
                      ansible_host: 10.6.33.23
                    DC1-POD2-LEAF3A:
                      type: l3leaf
                      ansible_host: 10.6.33.24
                    DC1-POD2-LEAF3B:
                      type: l3leaf
                      ansible_host: 10.6.33.25
                    DC1-POD2-LEAF4A:
                      type: l3leaf
                      ansible_host: 10.6.33.26
                    DC1-POD2-LEAF4B:
                      type: l3leaf
                      ansible_host: 10.6.33.27
                    DC1-POD2-LEAF5A:
                      type: l3leaf
                      ansible_host: 10.6.33.28
                    DC1-POD2-LEAF5B:
                      type: l3leaf
                      ansible_host: 10.6.33.29
                    DC1-POD2-LEAF6A:
                      type: l3leaf
                      ansible_host: 10.6.33.30
                    DC1-POD2-LEAF6B:
                      type: l3leaf
                      ansible_host: 10.6.33.31
                    DC1-POD2-LEAF7A:
                      type: l3leaf
                      ansible_host: 10.6.33.32
                    DC1-POD2-LEAF7B:
                      type: l3leaf
                      ansible_host: 10.6.33.33
                    DC1-POD2-LEAF8A:
                      type: l3leaf
                      ansible_host: 10.6.33.34
                    DC1-POD2-LEAF8B:
                      type: l3leaf
                      ansible_host: 10.6.33.35
                    DC1-POD2-LEAF9A:
                      type: l3leaf
                      ansible_host: 10.6.33.36
                    DC1-POD2-LEAF9B:
                      type: l3leaf
                      ansible_host: 10.6.33.37
                    DC1-POD2-LEAF10A:
                      type: l3leaf
                      ansible_host: 10.6.33.38
                    DC1-POD2-LEAF10B:
                      type: l3leaf
                      ansible_host: 10.6.33.39
                    DC1-POD2-LEAF11A:
                      type: l3leaf
                      ansible_host: 10.6.33.40
                    DC1-POD2-LEAF11B:
                      type: l3leaf
                      ansible_host: 10.6.33.41
                    DC1-POD2-LEAF12A:
                      type: l3leaf
                      ansible_host: 10.6.33.42
                    DC1-POD2-LEAF12B:
                      type: l3leaf
                      ansible_host: 10.6.33.43
                    DC1-POD2-LEAF13A:
                      type: l3leaf
                      ansible_host: 10.6.33.44
                    DC1-POD2-LEAF13B:
                      type: l3leaf
                      ansible_host: 10.6.33.45
                    DC1-POD2-LEAF14A:
                      type: l3leaf
                      ansible_host: 10.6.33.46
                    DC1-POD2-LEAF14B:
                      type: l3leaf
                      ansible_host: 10.6.33.47
        DC2:
          children:
            DC2_POD1:
              children:
                DC2_POD1_SPINES:
                  hosts:
                    DC2-POD1-SPINE1:
                      type: spine
                      ansible_host: 10.6.65.10
                    DC2-POD1-SPINE2:
                      type: spine
                      ansible_host: 10.6.65.11
                    DC2-POD1-SPINE3:
                      type: spine
                      ansible_host: 10.6.65.12
                    DC2-POD1-SPINE4:
                      type: spine
                      ansible_host: 10.6.65.13
                DC2_POD1_LEAFS:
                  hosts:
                    DC2-POD1-LEAF1A:
                      type: l3leaf
                      ansible_host: 10.6.35.20
                    DC2-POD1-LEAF1B:
                      type: l3leaf
                      ansible_host: 10.6.35.21
                    DC2-POD1-LEAF2A:
                      type: l3leaf
                      ansible_host: 10.6.35.22
                    DC2-POD1-LEAF2B:
                      type: l3leaf
                      ansible_host: 10.6.35.23
                    DC2-POD1-LEAF3A:
                      type: l3leaf
                      ansible_host: 10.6.35.24
                    DC2-POD1-LEAF3B:
                      type: l3leaf
                      ansible_host: 10.6.35.25
                    DC2-POD1-LEAF4A:
                      type: l3leaf
                      ansible_host: 10.6.35.26
                    DC2-POD1-LEAF4B:
                      type: l3leaf
                      ansible_host: 10.6.35.27
                    DC2-POD1-LEAF5A:
                      type: l3leaf
                      ansible_host: 10.6.35.28
                    DC2-POD1-LEAF5B:
                      type: l3leaf
                      ansible_host: 10.6.35.29
                    DC2-POD1-LEAF6A:
                      type: l3leaf
                      ansible_host: 10.6.35.30
                    DC2-POD1-LEAF6B:
                      type: l3leaf
                      ansible_host: 10.6.35.31
                    DC2-POD1-LEAF7A:
                      type: l3leaf
                      ansible_host: 10.6.35.32
                    DC2-POD1-LEAF7B:
                      type: l3leaf
                      ansible_host: 10.6.35.33
                    DC2-POD1-LEAF8A:
                      type: l3leaf
                      ansible_host: 10.6.35.34
                    DC2-POD1-LEAF8B:
                      type: l3leaf
                      ansible_host: 10.6.35.35
                    DC2-POD1-LEAF9A:
                      type: l3leaf
                      ansible_host: 10.6.35.36
                    DC2-POD1-LEAF9B:
                      type: l3leaf
                      ansible_host: 10.6.35.37
                    DC2-POD1-LEAF10A:
                      type: l3leaf
                      ansible_host: 10.6.35.38
                    DC2-POD1-LEAF10B:
                      type: l3leaf
                      ansible_host: 10.6.35.39
                    DC2-POD1-LEAF11A:
                      type: l3leaf
                      ansible_host: 10.6.35.40
                    DC2-POD1-LEAF11B:
                      type: l3leaf
                      ansible_host: 10.6.35.41
                    DC2-POD1-LEAF12A:
                      type: l3leaf
                      ansible_host: 10.6.35.42
                    DC2-POD1-LEAF12B:
                      type: l3leaf
                      ansible_host: 10.6.35.43
                    DC2-POD1-LEAF13A:
                      type: l3leaf
                      ansible_host: 10.6.35.44
                    DC2-POD1-LEAF13B:
                      type: l3leaf
                      ansible_host: 10.6.35.45
                    DC2-POD1-LEAF14A:
                      type: l3leaf
                      ansible_host: 10.6.35.46
                    DC2-POD1-LEAF14B:
                      type: l3leaf
                      ansible_host: 10.6.35.47

      vars:
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_host: '{{ ansible_host }}'
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        # ansible_network_os: arista.eos.eos
        ansible_user: cvpadmin
        ansible_ssh_pass: ChangeMe!@34
        ansible_become: true
        ansible_become_method: enable
        ansible_python_interpreter: $(which python3)
        cv_collection: v3

    # Needed for who can reference the values:
    TENANTS_NETWORKS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
        DC2_POD1_LEAFS:

    SERVERS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
        DC2_POD1_LEAFS:
    # Using this for edge's like mgmt
    ROUTERS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
    FIREWALLS:
      children:
        DC1_POD1_LEAFS:
        DC1_POD2_LEAFS:
