---
mgmt_gateway: 10.6.0.1
mgmt_interface: Management1
mgmt_interface_vrf: mgmt
mgmt_destination_networks:
  - 0.0.0.0/0

super_spine:
  defaults:
    platform: 7060DX4
    bgp_as: 650000
    loopback_ipv4_pool: 10.4.27.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    uplink_ptp:
      enable: true
  node_groups:
    DC1:
      mgmt_gateway: 10.6.5.1
      platform: 7060DX4
      spanning_tree_mode: none
      bgp_as: "64500"
      mlag: false
      evpn_role: none
      nodes:
        SUPER-SPINE1:
          id: 1
          bgp_as: 64501
          mgmt_ip: "10.6.0.10/24"
          mac_address: "00:01:02:03:04:05"
          # Next four lines don't have an impact
          mgmt_gateway: 192.168.0.1
          mgmt_interface: Management1
          mgmt_interface_vrf: mgmt
          mgmt_destination_networks:
            - 0.0.0.0/0
        SUPER-SPINE2:
          id: 2
          bgp_as: 64502
          mgmt_ip: "10.6.0.11/24"
          mac_address: "00:01:02:03:04:06"
        SUPER-SPINE3:
          id: 3
          bgp_as: 64503
          mgmt_ip: "10.6.0.12/24"
          mac_address: "00:01:02:03:04:07"
        SUPER-SPINE4:
          id: 4
          bgp_as: 64504
          mgmt_ip: "10.6.0.13/24"
          mac_address: "00:01:02:03:04:08"
          # SUPER-SPINE5:
          #   id: 5
          #   bgp_as: 64505
          #   mgmt_ip: "10.6.0.14/24"
          #   mac_address: "00:01:02:03:04:09"
