---
# original didn't have --- to start the file
- name: Configure DHCP Services
  hosts: dhcp_server
  gather_facts: true
  collections:
    - arista.cvp

  tasks:
    - name: Load vars file
      ansible.builtin.include_vars:
        file: /var/tmp/examples/blue-snakehead/inventory/ztp_dhcp_inventory.yml
    - name: Configure and enable DHCP services for ZTP provisioning
      ansible.builtin.import_role:
        name: arista.cvp.dhcp_configuration

# ---
# - name: Build Switch configuration
#   hosts: cv_server
#   connection: local
#   gather_facts: true
#   tasks:
#     - name: Create dhcp configuration file
#       import_role:
#           name: arista.avd.dhcp_provisioner
#       vars:
#         ztp_network_summary: 192.168.0.0/24
#         ztp_pool_start: 192.168.0.10
#         ztp_pool_end: 192.168.0.100
#         ztp_lease_time: 300
#         fabric_group: 'AMS'
#         ztp_mac_source: interface
#         ztp_mode: online
